[package]
name = "lab3"
version = "0.1.0"
edition = "2021"

[lib]
name = "lab3"
path = "src/lib.rs"

[features]
default = ["png"]
png = ["dep:png"]

[dependencies]
png = { version = "0.17.16", optional = true }
quick-xml = { version = "0.37.5", features = ["serialize"] }
serde = { version = "1.0.219", features = ["derive"] }
